### ISSUE TITLE
How to stream camera and preview Camera stream is you have any idea please tell me

### ISSUE THREAD

**Issue by rupamking1** [mateusfccp/magiceye#9]
How to stream camera and preview Camera stream is you have any idea please tell me

**Comment by mateusfccp** [comment]
Hi, @rupamking1.

Sorry, but I couldn't understand your question...

**Comment by rupamking1** [comment]
I want to make a video stream app,
One user send Camera Video stream and other receive stream & preview stream.
Do you know how that is possible?

**Comment by mateusfccp** [comment]
Hello, @rupamking1.

Unfortunately, `magiceye` won't be able to support you on this. Currently `magiceye` does not expose a video API. It is only possible to take pictures and not record videos.

However, I may be able to give you some tips on how to accomplish what you want.

There are two viable options for this case.
1. Use [WebRTC](https://github.com/flutter-webrtc/flutter-webrtc). It's a standard and open framework for real-time communication.
2. Alternatively, you can go with [AgoraIO](https://github.com/AgoraIO/Flutter-SDK). It builds upon WebRTC to make an easier and more simplified approach to the same problem. The main drawback is that it is a paid service. You have, however, 10.000 free minutes per month, which is enough for small cases and for developing/testing.

I hope this helps you with your problem?

**Comment by rupamking1** [comment]
no no I want to stream camera not video.
I want realtime camera stream User1 to User2, and User2 can see realtime image.

I find this code but that is not working-
void cameraBytesToDetector({@required CameraController camera}){
camera.startByteStream( (image) {
// do something with the image stream here
});
}

**Comment by mateusfccp** [comment]
Streaming camera is made by first recording the video in memory and them streaming. This is why I pointed that `magiceye` won't help you in this.

However, I already gave you two viable options, as this request is out of scope of this project.

**Comment by mateusfccp** [comment]
I am going to close this issue, as it seems both out of scope and solved.
